
-- Enum para roles de usuario
CREATE TYPE rol_enum AS ENUM ('ADMIN', 'PASAJERO', 'OPERADOR');

-- Tabla de usuarios
CREATE TABLE "Usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR NOT NULL,
  "correo" VARCHAR UNIQUE NOT NULL,
  "contraseña" VARCHAR NOT NULL,
  "rol" rol_enum NOT NULL
);

-- Tabla de choferes
CREATE TABLE "Chofer" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR NOT NULL,
  "dni" VARCHAR UNIQUE NOT NULL,
  "licencia" VARCHAR NOT NULL,
  "telefono" VARCHAR NOT NULL
);

-- Tabla de rutas
CREATE TABLE "Ruta" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR UNIQUE NOT NULL,
  "descripcion" TEXT
);

-- Tabla de puntos que forman la ruta (ordenados)
CREATE TABLE "RutaPunto" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ruta_id" INT REFERENCES "Ruta"(id) ON DELETE CASCADE,
  "orden" INT NOT NULL, -- orden del punto en la ruta
  "latitud" DECIMAL(9,6) NOT NULL CHECK (latitud BETWEEN -90 AND 90),
  "longitud" DECIMAL(9,6) NOT NULL CHECK (longitud BETWEEN -180 AND 180)
);

-- Tabla de estaciones
CREATE TABLE "Estacion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR NOT NULL,
  "latitud" DECIMAL(9,6) NOT NULL CHECK (latitud BETWEEN -90 AND 90),
  "longitud" DECIMAL(9,6) NOT NULL CHECK (longitud BETWEEN -180 AND 180),
  "distrito" VARCHAR NOT NULL
);

-- Tabla de buses
CREATE TABLE "Bus" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "placa" VARCHAR UNIQUE NOT NULL,
  "modelo" VARCHAR NOT NULL,
  "capacidad" INT NOT NULL CHECK (capacidad > 0),
  "estado" VARCHAR NOT NULL,
  "ruta_id" INT,
  "chofer_id" INT
);

-- Tabla intermedia entre ruta y estación (orden y distancia)
CREATE TABLE "RutaEstacion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ruta_id" INT NOT NULL,
  "estacion_id" INT NOT NULL,
  "orden" INT NOT NULL CHECK (orden > 0),
  "distancia_km" DECIMAL(5,2),
  CONSTRAINT ruta_estacion_unique UNIQUE (ruta_id, estacion_id)
);

-- Tabla de horarios por estación en ruta
CREATE TABLE "Horario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ruta_id" INT NOT NULL,
  "estacion_id" INT NOT NULL,
  "hora_estimada" TIME NOT NULL,
  CONSTRAINT horario_unique UNIQUE (ruta_id, estacion_id)
);

-- Ubicación en tiempo real del bus
CREATE TABLE "UbicacionBus" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bus_id" INT NOT NULL,
  "latitud" DECIMAL(9,6),
  "longitud" DECIMAL(9,6),
  "velocidad" DECIMAL(5,2),
  "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Historial de pasos del bus por estación
CREATE TABLE "HistorialViaje" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bus_id" INT NOT NULL,
  "estacion_id" INT NOT NULL,
  "fecha_hora_paso" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  "ruta_id" INT NOT NULL
);

-- Claves foráneas
ALTER TABLE "Bus" ADD FOREIGN KEY ("ruta_id") REFERENCES "Ruta" ("id") ON DELETE CASCADE;
ALTER TABLE "Bus" ADD FOREIGN KEY ("chofer_id") REFERENCES "Chofer" ("id") ON DELETE CASCADE;

ALTER TABLE "RutaEstacion" ADD FOREIGN KEY ("ruta_id") REFERENCES "Ruta" ("id") ON DELETE CASCADE;
ALTER TABLE "RutaEstacion" ADD FOREIGN KEY ("estacion_id") REFERENCES "Estacion" ("id") ON DELETE CASCADE;

ALTER TABLE "Horario" ADD FOREIGN KEY ("ruta_id") REFERENCES "Ruta" ("id") ON DELETE CASCADE;
ALTER TABLE "Horario" ADD FOREIGN KEY ("estacion_id") REFERENCES "Estacion" ("id") ON DELETE CASCADE;

ALTER TABLE "UbicacionBus" ADD FOREIGN KEY ("bus_id") REFERENCES "Bus" ("id") ON DELETE CASCADE;

ALTER TABLE "HistorialViaje" ADD FOREIGN KEY ("bus_id") REFERENCES "Bus" ("id") ON DELETE CASCADE;
ALTER TABLE "HistorialViaje" ADD FOREIGN KEY ("estacion_id") REFERENCES "Estacion" ("id") ON DELETE CASCADE;
ALTER TABLE "HistorialViaje" ADD FOREIGN KEY ("ruta_id") REFERENCES "Ruta" ("id") ON DELETE CASCADE;
